stages:
  get_data:
    cmd: wget -O a1_RestaurantReviews_HistoricDump.tsv 
      https://github.com/proksch/restaurant-sentiment/raw/refs/heads/main/a1_RestaurantReviews_HistoricDump.tsv
    outs:
    - a1_RestaurantReviews_HistoricDump.tsv
  preprocess:
    cmd: python -m review_rating.modeling prepare a1_RestaurantReviews_HistoricDump.tsv
      -o output -t 0.1
    deps:
    - review_rating/
    outs:
    - output/processed_data.pk1
    - output/vectorizer.pkl
  train:
    cmd: python -m review_rating.modeling train --input-dir output --output-model
      output/
    deps:
    - review_rating/
    outs:
    - output/model-gauss.jbl
    - output/model-multi.jbl
  analyze:
    cmd: python -m review_rating.modeling evaluate --input-dir output --model-path
      output/ --metrics-path output/metrics.json
    deps:
    - review_rating/
    outs:
    - output/metrics.json

metrics:
- output/metrics.json
params:
- dvclive/params.yaml
artifacts:
  model-multi:
    path: processed/model-multi.jbl
    type: model
  model-gauss:
    path: processed/model-gauss.jbl
    type: model
