stages:
  get_data:
    cmd: python training/get_data.py
    deps:
    - training/get_data.py
  preprocess:
    cmd: python training/preprocessing.py
    deps:
    - training/preprocessing.py
    outs:
    - output/corpus.jbl
    - output/labels.jbl
  vectorize:
    cmd: VECTORIZER_MAX_FEATURES=1420 TEST_SIZE=0.20 RNG_STATE=42 python training/build_vectorizer.py
    deps:
    - training/build_vectorizer.py
    outs:
    - output/vectorizer.jbl
    - output/splits/X_train.jbl
    - output/splits/X_test.jbl
    - output/splits/y_train.jbl
    - output/splits/y_test.jbl
  train:
    cmd: python training/train_model.py
    deps:
    - training/train_model.py
    outs:
    - output/model-gauss.jbl
    - output/model-multi.jbl
  analyze:
    cmd: python training/get_metrics.py
    deps:
    - training/get_metrics.py
    outs:
    - output/metrics.json
metrics:
- output/metrics.json
params:
- dvclive/params.yaml
artifacts:
  model:
    path: output/model-gauss.jbl
    type: model
  model-multi:
    path: output/model-multi.jbl
    type: model
