# This file is restructured with the help of ChatGPT
name: Continuous Integration

on:
  push:
    branches: [ "**" ]  # All branches

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      #basic pytest and pylint, will be extended later
      - name: Run tests with coverage
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest --cov=review_rating review_rating

      - name: Generate coverage report
        run: |
          coverage xml
          coverage html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
      
      - name: Run pylint and update badge with gradient color
        env:
          PYTHONPATH: .
        run: |
          pip install pylint bc
          pylint review_rating/modeling review_rating/tests --rcfile=.pylintrc --score=y > pylint_output.txt || true
          SCORE=$(grep "Your code has been rated at" pylint_output.txt | awk '{print $7}' | cut -d'/' -f1)
          SCORE_CLEAN=$(printf "%.2f" "$SCORE")
      
          # Set badge color gradient
          if (( $(echo "$SCORE >= 9.5" | bc -l) )); then
            COLOR="brightgreen"
          elif (( $(echo "$SCORE >= 8.5" | bc -l) )); then
            COLOR="green"
          elif (( $(echo "$SCORE >= 7.5" | bc -l) )); then
            COLOR="yellowgreen"
          elif (( $(echo "$SCORE >= 6.5" | bc -l) )); then
            COLOR="yellow"
          elif (( $(echo "$SCORE >= 5.0" | bc -l) )); then
            COLOR="orange"
          else
            COLOR="red"
          fi
      
          BADGE="![pylint](https://img.shields.io/badge/PyLint-${SCORE_CLEAN}-${COLOR}?logo=python&logoColor=white)"
      
          sed -i "s|!\[pylint\](.*)|${BADGE}|" README.md || echo "No badge found to replace"
            
      - name: Commit updated README badge
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update pylint badge score to ${SCORE_CLEAN}" || echo "No changes"
          git push || echo "Skipping push on PR"

      - name: Update test coverage badge
        run: |
          COVERAGE=$(coverage report | grep TOTAL | awk '{print $4}' | sed 's/%//')
          COVERAGE_CLEAN=$(printf "%.0f" "$COVERAGE")
      
          # Set badge color gradient
          if (( $(echo "$COVERAGE_CLEAN >= 90" | bc -l) )); then
            COLOR="brightgreen"
          elif (( $(echo "$COVERAGE_CLEAN >= 75" | bc -l) )); then
            COLOR="green"
          elif (( $(echo "$COVERAGE_CLEAN >= 50" | bc -l) )); then
            COLOR="yellow"
          else
            COLOR="red"
          fi
      
          # Create badge
          BADGE="![coverage](https://img.shields.io/badge/Coverage-${COVERAGE_CLEAN}%25-${COLOR}?logo=pytest&logoColor=white)"
      
          # Replace in README
          sed -i "s|!\[coverage\](.*)|${BADGE}|" README.md || echo "No coverage badge found to replace"

      - name: Commit coverage badge
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update coverage badge" || echo "No changes"
          git push || echo "Skipping push on PR"
          
      - name: Run flake8
        run: |
          pip install flake8
          flake8 review_rating

      - name: Run Bandit
        run: |
          pip install bandit
          bandit -r review_rating -c bandit.yaml


      - name: Calculate ML Test Score (by test files)
        run: |
          echo "## ML Test Score Summary"
      
          pytest tests/test_features_and_data.py | tee >(grep -c "PASSED" > .score_feature)
          pytest tests/test_model.py | tee >(grep -c "PASSED" > .score_model)
          pytest tests/test_infrastructure.py | tee >(grep -c "PASSED" > .score_infra)
          pytest tests/test_monitoring.py | tee >(grep -c "PASSED" > .score_monitor)
      
          score=0
          [ $(cat .score_feature) -gt 0 ] && score=$((score+1))
          [ $(cat .score_model) -gt 0 ] && score=$((score+1))
          [ $(cat .score_infra) -gt 0 ] && score=$((score+1))
          [ $(cat .score_monitor) -gt 0 ] && score=$((score+1))
      
          echo "Final ML Test Score: $score/4"
          echo "ml_score=$score" >> $GITHUB_ENV
  
      - name: Save ML score to file
        run: |
          echo "$score" > ml_score.txt

      - name: Commit updated ML score
        run: |
          mkdir -p metrics
          mv ml_score.txt metrics/ml_score.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add metrics/ml_score.txt
          git commit -m "Update ML score"
          git push
        
