name: Continuous Integration

on:
  push:
    branches: [*]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      #basic pytest and pylint, will be extended later
      - name: Run tests with coverage
        run: |
          pytest --cov=training tests/  

      - name: Run pylint
        run: |
          pylint training 
          
      - name: Generate coverage report
        run: |
          coverage xml
          coverage html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
