name: Release Model

on:
  push:
    tags:
      - 'v*.*.*'  # e.g., v1.0.0
    branches:
      - main  # Only run on pushes to the main branch
  pull_request:
    branches:
      - main  # Only run on pull requests to the main branch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get release version the git status
      id: get_version
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          echo "Tagged release detected."
          VERSION="${GITHUB_REF#refs/tags/}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "prerelease=false" >> "$GITHUB_OUTPUT"
          echo "tagged=true" >> "$GITHUB_OUTPUT"
        else
          echo "Not a tagged release. Extracting prerelease version"
          VERSION="$(./get_semver.sh)"
          echo "Version: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "prerelease=true" >> "$GITHUB_OUTPUT"
          echo "tagged=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Automatically download the dataset
      run:
        wget -O a1_RestaurantReviews_HistoricDump.tsv https://github.com/proksch/restaurant-sentiment/raw/refs/heads/main/a1_RestaurantReviews_HistoricDump.tsv

    - name: Run data preparation
      run: |
        python -m review_rating.modeling prepare a1_RestaurantReviews_HistoricDump.tsv -o . -t 0.1

    - name: Run training
      run: |
        python -m review_rating.modeling train --input-dir . --output-model model.pkl

    - name: Run evaluation
      run: |
        python -m review_rating.modeling evaluate --input-dir . --model-path model.pkl


    - name: Upload training artifacts
      uses: actions/upload-artifact@v4
      with:
        name: training-artifacts
        path: |
          vectorizer.pkl
          model.pkl
      if: github.ref_type == 'tag' || github.ref == 'refs/heads/main'


    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        name: ${{ steps.get_version.outputs.version }}
        body: |
          Automated release of the model.
          Version: ${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: ${{ steps.get_version.outputs.prerelease }}
        make_latest: ${{ steps.get_version.outputs.tagged }}
        files: |
          model.pkl
          vectorizer.pkl
      if: github.ref_type == 'tag' || github.ref == 'refs/heads/main'
